package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to     get the bean     called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PostMapping(path="/add") // It maps only Post requests
	public @ResponseBody String addNewUser(@RequestBody User userRequest) {
		User user = new User();
		user.setName(userRequest.getName());
		user.setEmail(userRequest.getEmail());

		// Convert Map to List of UserProperty objects
		List<UserProperty> properties = new ArrayList<>();
		for (UserProperty prop : userRequest.getProperties()) {
			prop.setUser(user); // Ensure bidirectional link
			properties.add(prop);
		}

		user.setProperties(properties);
		userRepository.save(user);
		return "Saved";
	}

	@GetMapping(path="/all") // It maps only Get requests
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
